/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace AssetRegistry {
      
    export type AssetInfoStruct = {tokenAddress: AddressLike, assetId: string, assetType: string, name: string, status: BigNumberish, registeredAt: BigNumberish}

    export type AssetInfoStructOutput = [tokenAddress: string, assetId: string, assetType: string, name: string, status: bigint, registeredAt: bigint] & {tokenAddress: string, assetId: string, assetType: string, name: string, status: bigint, registeredAt: bigint }
  
    }

  export interface AssetRegistryInterface extends Interface {
    getFunction(nameOrSignature: "ADMIN_ROLE" | "DEFAULT_ADMIN_ROLE" | "getAllAssetIds" | "getAssetCount" | "getAssetIdByToken" | "getAssetInfo" | "getAssetTokenAddress" | "getAssetsByType" | "getRoleAdmin" | "grantRole" | "hasRole" | "isAssetRegistered" | "registerAsset" | "renounceRole" | "revokeRole" | "supportsInterface" | "updateAssetStatus"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AssetRegistered" | "AssetStatusUpdated" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked"): EventFragment;

    encodeFunctionData(functionFragment: 'ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAllAssetIds', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAssetCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAssetIdByToken', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getAssetInfo', values: [string]): string;
encodeFunctionData(functionFragment: 'getAssetTokenAddress', values: [string]): string;
encodeFunctionData(functionFragment: 'getAssetsByType', values: [string]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isAssetRegistered', values: [string]): string;
encodeFunctionData(functionFragment: 'registerAsset', values: [AddressLike, string, string, string]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'updateAssetStatus', values: [string, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllAssetIds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAssetCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAssetIdByToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAssetInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAssetTokenAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAssetsByType', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isAssetRegistered', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerAsset', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateAssetStatus', data: BytesLike): Result;
  }

  
    export namespace AssetRegisteredEvent {
      export type InputTuple = [assetId: string, tokenAddress: AddressLike, assetType: string, name: string];
      export type OutputTuple = [assetId: string, tokenAddress: string, assetType: string, name: string];
      export interface OutputObject {assetId: string, tokenAddress: string, assetType: string, name: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AssetStatusUpdatedEvent {
      export type InputTuple = [assetId: string, newStatus: BigNumberish];
      export type OutputTuple = [assetId: string, newStatus: bigint];
      export interface OutputObject {assetId: string, newStatus: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AssetRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): AssetRegistry;
    waitForDeployment(): Promise<this>;

    interface: AssetRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getAllAssetIds: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getAssetCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getAssetIdByToken: TypedContractMethod<
      [tokenAddress: AddressLike, ],
      [string],
      'view'
    >
    

    
    getAssetInfo: TypedContractMethod<
      [assetId: string, ],
      [AssetRegistry.AssetInfoStructOutput],
      'view'
    >
    

    
    getAssetTokenAddress: TypedContractMethod<
      [assetId: string, ],
      [string],
      'view'
    >
    

    
    getAssetsByType: TypedContractMethod<
      [assetType: string, ],
      [string[]],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isAssetRegistered: TypedContractMethod<
      [assetId: string, ],
      [boolean],
      'view'
    >
    

    
    registerAsset: TypedContractMethod<
      [tokenAddress: AddressLike, assetId: string, assetType: string, name: string, ],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    updateAssetStatus: TypedContractMethod<
      [assetId: string, newStatus: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getAllAssetIds'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getAssetCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getAssetIdByToken'): TypedContractMethod<
      [tokenAddress: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getAssetInfo'): TypedContractMethod<
      [assetId: string, ],
      [AssetRegistry.AssetInfoStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getAssetTokenAddress'): TypedContractMethod<
      [assetId: string, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getAssetsByType'): TypedContractMethod<
      [assetType: string, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isAssetRegistered'): TypedContractMethod<
      [assetId: string, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'registerAsset'): TypedContractMethod<
      [tokenAddress: AddressLike, assetId: string, assetType: string, name: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'updateAssetStatus'): TypedContractMethod<
      [assetId: string, newStatus: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AssetRegistered'): TypedContractEvent<AssetRegisteredEvent.InputTuple, AssetRegisteredEvent.OutputTuple, AssetRegisteredEvent.OutputObject>;
getEvent(key: 'AssetStatusUpdated'): TypedContractEvent<AssetStatusUpdatedEvent.InputTuple, AssetStatusUpdatedEvent.OutputTuple, AssetStatusUpdatedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;

    filters: {
      
      'AssetRegistered(string,address,string,string)': TypedContractEvent<AssetRegisteredEvent.InputTuple, AssetRegisteredEvent.OutputTuple, AssetRegisteredEvent.OutputObject>;
      AssetRegistered: TypedContractEvent<AssetRegisteredEvent.InputTuple, AssetRegisteredEvent.OutputTuple, AssetRegisteredEvent.OutputObject>;
    

      'AssetStatusUpdated(string,uint8)': TypedContractEvent<AssetStatusUpdatedEvent.InputTuple, AssetStatusUpdatedEvent.OutputTuple, AssetStatusUpdatedEvent.OutputObject>;
      AssetStatusUpdated: TypedContractEvent<AssetStatusUpdatedEvent.InputTuple, AssetStatusUpdatedEvent.OutputTuple, AssetStatusUpdatedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    
    };
  }