/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface MilestoneEscrowInterface extends Interface {
    getFunction(nameOrSignature: "beneficiary" | "configureAsset" | "deposit" | "getMilestone" | "inspector" | "milestoneCount" | "owner" | "releaseMilestone" | "renounceOwnership" | "setInspector" | "totalDeposited" | "totalReleased" | "transferOwnership" | "usdc"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AssetConfigured" | "Deposited" | "MilestoneReleased" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'beneficiary', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'configureAsset', values: [AddressLike, AddressLike, BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'deposit', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getMilestone', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'inspector', values?: undefined): string;
encodeFunctionData(functionFragment: 'milestoneCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'releaseMilestone', values: [AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setInspector', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'totalDeposited', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'totalReleased', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'usdc', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'beneficiary', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'configureAsset', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMilestone', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'inspector', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'milestoneCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseMilestone', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setInspector', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalDeposited', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalReleased', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdc', data: BytesLike): Result;
  }

  
    export namespace AssetConfiguredEvent {
      export type InputTuple = [assetToken: AddressLike, beneficiary: AddressLike, milestoneCount: BigNumberish];
      export type OutputTuple = [assetToken: string, beneficiary: string, milestoneCount: bigint];
      export interface OutputObject {assetToken: string, beneficiary: string, milestoneCount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DepositedEvent {
      export type InputTuple = [assetToken: AddressLike, from: AddressLike, amount: BigNumberish];
      export type OutputTuple = [assetToken: string, from: string, amount: bigint];
      export interface OutputObject {assetToken: string, from: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MilestoneReleasedEvent {
      export type InputTuple = [assetToken: AddressLike, index: BigNumberish, amount: BigNumberish, proofHash: BytesLike];
      export type OutputTuple = [assetToken: string, index: bigint, amount: bigint, proofHash: string];
      export interface OutputObject {assetToken: string, index: bigint, amount: bigint, proofHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MilestoneEscrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): MilestoneEscrow;
    waitForDeployment(): Promise<this>;

    interface: MilestoneEscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    beneficiary: TypedContractMethod<
      [assetToken: AddressLike, ],
      [string],
      'view'
    >
    

    
    configureAsset: TypedContractMethod<
      [assetToken: AddressLike, _beneficiary: AddressLike, releaseBps: BigNumberish[], ],
      [void],
      'nonpayable'
    >
    

    
    deposit: TypedContractMethod<
      [assetToken: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getMilestone: TypedContractMethod<
      [assetToken: AddressLike, index: BigNumberish, ],
      [[bigint, boolean, string] & {releaseBps: bigint, released: boolean, proofHash: string }],
      'view'
    >
    

    
    inspector: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    milestoneCount: TypedContractMethod<
      [assetToken: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    releaseMilestone: TypedContractMethod<
      [assetToken: AddressLike, index: BigNumberish, proofHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setInspector: TypedContractMethod<
      [i: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    totalDeposited: TypedContractMethod<
      [assetToken: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    totalReleased: TypedContractMethod<
      [assetToken: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    usdc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'beneficiary'): TypedContractMethod<
      [assetToken: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'configureAsset'): TypedContractMethod<
      [assetToken: AddressLike, _beneficiary: AddressLike, releaseBps: BigNumberish[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [assetToken: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getMilestone'): TypedContractMethod<
      [assetToken: AddressLike, index: BigNumberish, ],
      [[bigint, boolean, string] & {releaseBps: bigint, released: boolean, proofHash: string }],
      'view'
    >;
getFunction(nameOrSignature: 'inspector'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'milestoneCount'): TypedContractMethod<
      [assetToken: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'releaseMilestone'): TypedContractMethod<
      [assetToken: AddressLike, index: BigNumberish, proofHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setInspector'): TypedContractMethod<
      [i: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalDeposited'): TypedContractMethod<
      [assetToken: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalReleased'): TypedContractMethod<
      [assetToken: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usdc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'AssetConfigured'): TypedContractEvent<AssetConfiguredEvent.InputTuple, AssetConfiguredEvent.OutputTuple, AssetConfiguredEvent.OutputObject>;
getEvent(key: 'Deposited'): TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
getEvent(key: 'MilestoneReleased'): TypedContractEvent<MilestoneReleasedEvent.InputTuple, MilestoneReleasedEvent.OutputTuple, MilestoneReleasedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'AssetConfigured(address,address,uint256)': TypedContractEvent<AssetConfiguredEvent.InputTuple, AssetConfiguredEvent.OutputTuple, AssetConfiguredEvent.OutputObject>;
      AssetConfigured: TypedContractEvent<AssetConfiguredEvent.InputTuple, AssetConfiguredEvent.OutputTuple, AssetConfiguredEvent.OutputObject>;
    

      'Deposited(address,address,uint256)': TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
      Deposited: TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
    

      'MilestoneReleased(address,uint256,uint256,bytes32)': TypedContractEvent<MilestoneReleasedEvent.InputTuple, MilestoneReleasedEvent.OutputTuple, MilestoneReleasedEvent.OutputObject>;
      MilestoneReleased: TypedContractEvent<MilestoneReleasedEvent.InputTuple, MilestoneReleasedEvent.OutputTuple, MilestoneReleasedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }