/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace PayoutDistributor {
      
    export type DistributionStruct = {snapshotId: BigNumberish, totalAmount: BigNumberish, amountPerToken: BigNumberish, timestamp: BigNumberish, finalized: boolean}

    export type DistributionStructOutput = [snapshotId: bigint, totalAmount: bigint, amountPerToken: bigint, timestamp: bigint, finalized: boolean] & {snapshotId: bigint, totalAmount: bigint, amountPerToken: bigint, timestamp: bigint, finalized: boolean }
  
    }

  export interface PayoutDistributorInterface extends Interface {
    getFunction(nameOrSignature: "ADMIN_ROLE" | "DEFAULT_ADMIN_ROLE" | "claimYield" | "claimed" | "distributeYield" | "distributions" | "emergencyWithdraw" | "getClaimableYield" | "getDistribution" | "getDistributionCount" | "getRoleAdmin" | "grantRole" | "hasRole" | "renounceRole" | "revokeRole" | "supportsInterface" | "usdcToken"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "YieldClaimed" | "YieldDistributed"): EventFragment;

    encodeFunctionData(functionFragment: 'ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'claimYield', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'claimed', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'distributeYield', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'distributions', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'emergencyWithdraw', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getClaimableYield', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'getDistribution', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getDistributionCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'usdcToken', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimYield', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'distributeYield', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'distributions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emergencyWithdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getClaimableYield', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDistribution', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDistributionCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdcToken', data: BytesLike): Result;
  }

  
    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace YieldClaimedEvent {
      export type InputTuple = [user: AddressLike, assetToken: AddressLike, amount: BigNumberish, distributionIndex: BigNumberish];
      export type OutputTuple = [user: string, assetToken: string, amount: bigint, distributionIndex: bigint];
      export interface OutputObject {user: string, assetToken: string, amount: bigint, distributionIndex: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace YieldDistributedEvent {
      export type InputTuple = [assetToken: AddressLike, totalAmount: BigNumberish, snapshotId: BigNumberish, distributionIndex: BigNumberish];
      export type OutputTuple = [assetToken: string, totalAmount: bigint, snapshotId: bigint, distributionIndex: bigint];
      export interface OutputObject {assetToken: string, totalAmount: bigint, snapshotId: bigint, distributionIndex: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PayoutDistributor extends BaseContract {
    
    connect(runner?: ContractRunner | null): PayoutDistributor;
    waitForDeployment(): Promise<this>;

    interface: PayoutDistributorInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    claimYield: TypedContractMethod<
      [assetToken: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    claimed: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    distributeYield: TypedContractMethod<
      [assetToken: AddressLike, totalAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    distributions: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, boolean] & {snapshotId: bigint, totalAmount: bigint, amountPerToken: bigint, timestamp: bigint, finalized: boolean }],
      'view'
    >
    

    
    emergencyWithdraw: TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getClaimableYield: TypedContractMethod<
      [assetToken: AddressLike, user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getDistribution: TypedContractMethod<
      [assetToken: AddressLike, index: BigNumberish, ],
      [PayoutDistributor.DistributionStructOutput],
      'view'
    >
    

    
    getDistributionCount: TypedContractMethod<
      [assetToken: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    usdcToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'claimYield'): TypedContractMethod<
      [assetToken: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimed'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'distributeYield'): TypedContractMethod<
      [assetToken: AddressLike, totalAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'distributions'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, boolean] & {snapshotId: bigint, totalAmount: bigint, amountPerToken: bigint, timestamp: bigint, finalized: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'emergencyWithdraw'): TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getClaimableYield'): TypedContractMethod<
      [assetToken: AddressLike, user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getDistribution'): TypedContractMethod<
      [assetToken: AddressLike, index: BigNumberish, ],
      [PayoutDistributor.DistributionStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getDistributionCount'): TypedContractMethod<
      [assetToken: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'usdcToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'YieldClaimed'): TypedContractEvent<YieldClaimedEvent.InputTuple, YieldClaimedEvent.OutputTuple, YieldClaimedEvent.OutputObject>;
getEvent(key: 'YieldDistributed'): TypedContractEvent<YieldDistributedEvent.InputTuple, YieldDistributedEvent.OutputTuple, YieldDistributedEvent.OutputObject>;

    filters: {
      
      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'YieldClaimed(address,address,uint256,uint256)': TypedContractEvent<YieldClaimedEvent.InputTuple, YieldClaimedEvent.OutputTuple, YieldClaimedEvent.OutputObject>;
      YieldClaimed: TypedContractEvent<YieldClaimedEvent.InputTuple, YieldClaimedEvent.OutputTuple, YieldClaimedEvent.OutputObject>;
    

      'YieldDistributed(address,uint256,uint256,uint256)': TypedContractEvent<YieldDistributedEvent.InputTuple, YieldDistributedEvent.OutputTuple, YieldDistributedEvent.OutputObject>;
      YieldDistributed: TypedContractEvent<YieldDistributedEvent.InputTuple, YieldDistributedEvent.OutputTuple, YieldDistributedEvent.OutputObject>;
    
    };
  }